### ISSUE TITLE
Volume control

### ISSUE THREAD

**Issue by ThoSanLinhHon** [fbiego/chronos-esp32#1]
This is a perfect library for me. But after searching, I can't find the volume control command.
Do you have any suggestions for this feature? I found the list of multimedia commands in the .h file but I don't know the volume control code

**Comment by fbiego** [comment]
Thanks for your suggestion. This feature is not yet available on the app side but I will consider integrating it.

**Comment by fbiego** [comment]
this has now been added to the library however it still needs to be implemented on the app side. You should expect this in the next version of Chronos app v2.9.0+

**Comment by fbiego** [comment]
Chronos v2.9.0 has been released on Google Play

**Comment by ThoSanLinhHon** [comment]
Thank you! In my opinion, this is the simplest and most stable library. Currently I am using this library to implement a control device for motorbike drivers. In fact, this was only possible when I learned about your library. Thank you very much!
